title: Eleventy Simple Starter Template
description: Minimal eleventy template with basic configuration for pages and posts
author: Tim Gilpin
locale: en_GB
image: /static/img/496404201.jpg
imageWidth: 1280
imageHeight: 630
imageAlt: Screenshot of website at https://timgilp.in
#  overrides default `posts`
postsUrl: articles